#!/bin/bash

cd $STEAM_FORCE_INSTALL

sed -i "s/REPLACEME_CONTROLPANEL_PASSWORD/$REPLACEME_CONTROLPANEL_PASSWORD/" ./serverconfig_template.xml
sed -i "s/REPLACEME_TELNET_PASSWORD/$REPLACEME_TELNET_PASSWORD/" ./serverconfig_template.xml
